[tool]
id = "com.thelightphone.transit"
label = "Pico Transit"
versionCode = 11
versionName = "0.5.1"
permissions = ["android.permission.INTERNET", "android.permission.ACCESS_NETWORK_STATE", "android.permission.ACCESS_FINE_LOCATION"]
capabilities = []
orientation = "portrait"
serverPackage = "com.lightos"
# for emulator builds instead:
# serverPackage = "com.thelightphone.sdk.emulator"
