[tool]
id = "com.thelightphone.transit"
label = "Pico Transit"
versionCode = 4
versionName = "0.2.5"
permissions = ["android.permission.INTERNET", "android.permission.ACCESS_NETWORK_STATE"]
capabilities = []
serverPackage = "com.lightos"
# for emulator builds instead:
# serverPackage = "com.thelightphone.sdk.emulator"
